# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{lib, ...}: {
  boot = {
    initrd = {
      availableKernelModules = ["virtio_pci"];
      kernelModules = [];
    };
    kernelModules = ["kvm-intel"];
    extraModulePackages = [];
  };

  fileSystems = {
    "/mnt/wsl" = {
      device = "none";
      fsType = "tmpfs";
    };

    "/usr/lib/wsl/drivers" = {
      device = "drivers";
      fsType = "9p";
    };

    "/lib/modules" = {
      device = "none";
      fsType = "tmpfs";
    };

    "/" = {
      device = "/dev/disk/by-uuid/7a1d55dd-a7ec-4263-86d3-23edcf912572";
      fsType = "ext4";
    };

    "/mnt/wslg" = {
      device = "none";
      fsType = "tmpfs";
    };

    "/mnt/wslg/distro" = {
      device = "none";
      fsType = "none";
      options = ["bind"];
    };

    "/usr/lib/wsl/lib" = {
      device = "none";
      fsType = "overlay";
    };

    "/tmp/.X11-unix" = {
      device = "/mnt/wslg/.X11-unix";
      fsType = "none";
      options = ["bind"];
    };

    "/mnt/wslg/doc" = {
      device = "none";
      fsType = "overlay";
    };

    "/mnt/c" = {
      device = "C:\134";
      fsType = "9p";
    };
  };

  # fileSystems."/mnt/d" = {
  #   device = "D:\134";
  #   fsType = "9p";
  # };

  swapDevices = [
    {device = "/dev/disk/by-uuid/26624da5-1cb6-47a1-a442-ed16f315174a";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eth0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
