# Placeholder hardware config — regenerated by nixos-anywhere
# --generate-hardware-config on the real box (Ryzen 7 5700U mini PC, NVMe, Intel
# I225-V NIC). Commit the generated file after first install. disko provides
# fileSystems + the boot loader.
{ lib, ... }:
{
  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  networking.useDHCP = lib.mkDefault true;
}
