# Placeholder hardware config — regenerated by nixos-anywhere
# --generate-hardware-config on the real box (bare-metal dedicated server, NOT a
# qemu guest). Commit the generated file after first install. The modules below
# are a generic bare-metal starting set (SATA/NVMe/USB + Intel KVM); disko
# provides fileSystems and the boot loader.
{ lib, ... }:
{
  boot.initrd.availableKernelModules = [
    "ahci"
    "xhci_pci"
    "ehci_pci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  networking.useDHCP = lib.mkDefault true;
}
