#!/usr/bin/env python3
"""Extract the Zen/Firefox bookmarks toolbar + menu + other roots into a
home-manager `programs.firefox.profiles.<p>.bookmarks.settings` Nix list.

stdlib only. Reads <profile>/places.sqlite (copied to a temp dir to dodge the
live WAL lock) and writes a Nix expression to --output (default: stdout).

Usage:
  zen-bookmarks-to-nix.py [--profile ~/.zen/Default] [--output FILE]
"""
import argparse
import os
import shutil
import sqlite3
import sys
import tempfile

TYPE_BOOKMARK, TYPE_FOLDER, TYPE_SEPARATOR = 1, 2, 3
ROOTS = [
    ("toolbar_____", "Bookmarks Toolbar", True),
    ("menu________", None, False),          # menu children float to top level
    ("unfiled_____", "Other Bookmarks", False),
]


def nix_str(s):
    s = s.replace("\\", "\\\\").replace('"', '\\"').replace("${", "\\${")
    return '"' + s + '"'


def open_places(profile):
    src = os.path.join(os.path.expanduser(profile), "places.sqlite")
    if not os.path.exists(src):
        sys.exit(f"error: no places.sqlite at {src}")
    td = tempfile.mkdtemp(prefix="zenbm-")
    dst = os.path.join(td, "places.sqlite")
    shutil.copy(src, dst)
    for ext in ("-wal", "-shm"):
        if os.path.exists(src + ext):
            shutil.copy(src + ext, dst + ext)
    return sqlite3.connect(dst), td


def root_id(cur, guid):
    cur.execute("SELECT id FROM moz_bookmarks WHERE guid=?", (guid,))
    r = cur.fetchone()
    return r[0] if r else None


def keyword_for(cur, place_id):
    cur.execute("SELECT keyword FROM moz_keywords WHERE place_id=? LIMIT 1", (place_id,))
    r = cur.fetchone()
    return r[0] if r else None


def build_nodes(cur, parent_id):
    cur.execute(
        "SELECT id, type, title, fk FROM moz_bookmarks WHERE parent=? ORDER BY position",
        (parent_id,),
    )
    rows = cur.fetchall()
    nodes = []
    for bid, btype, title, fk in rows:
        if btype == TYPE_SEPARATOR:
            nodes.append("separator")
        elif btype == TYPE_BOOKMARK:
            cur.execute("SELECT url FROM moz_places WHERE id=?", (fk,))
            r = cur.fetchone()
            url = r[0] if r else None
            if not url or url.startswith("place:"):
                continue
            entry = {"name": title or url, "url": url}
            kw = keyword_for(cur, fk)
            if kw:
                entry["keyword"] = kw
            nodes.append(entry)
        elif btype == TYPE_FOLDER:
            nodes.append({"dir": True, "name": title or "", "bookmarks": build_nodes(cur, bid)})
    return nodes


def render(node, indent):
    pad = "  " * indent
    if node == "separator":
        return f'{pad}"separator"'
    if node.get("dir"):
        lines = [f"{pad}{{", f"{pad}  name = {nix_str(node['name'])};"]
        if node.get("toolbar"):
            lines.append(f"{pad}  toolbar = true;")
        lines.append(f"{pad}  bookmarks = [")
        for child in node["bookmarks"]:
            lines.append(render(child, indent + 2))
        lines.append(f"{pad}  ];")
        lines.append(f"{pad}}}")
        return "\n".join(lines)
    lines = [f"{pad}{{", f"{pad}  name = {nix_str(node['name'])};"]
    if "keyword" in node:
        lines.append(f"{pad}  keyword = {nix_str(node['keyword'])};")
    lines.append(f"{pad}  url = {nix_str(node['url'])};")
    lines.append(f"{pad}}}")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--profile", default="~/.zen/Default")
    ap.add_argument("--output", default="-")
    args = ap.parse_args()

    conn, td = open_places(args.profile)
    try:
        cur = conn.cursor()
        settings = []
        for guid, label, is_toolbar in ROOTS:
            rid = root_id(cur, guid)
            if rid is None:
                continue
            children = build_nodes(cur, rid)
            if is_toolbar:
                settings.append({"dir": True, "name": label, "toolbar": True, "bookmarks": children})
            elif label is None:
                settings.extend(children)  # menu -> top level (Bookmarks Menu)
            elif children:
                settings.append({"dir": True, "name": label, "bookmarks": children})
    finally:
        conn.close()
        shutil.rmtree(td, ignore_errors=True)

    body = "\n".join(render(n, 1) for n in settings)
    text = (
        "# Generated by scripts/zen-bookmarks-to-nix.py from ~/.zen/Default/places.sqlite.\n"
        "# Re-run that script to refresh. Consumed as\n"
        "# programs.firefox.profiles.Default.bookmarks.settings (see hosts/common/home/zen).\n"
        "[\n" + body + "\n]\n"
    )
    if args.output == "-":
        sys.stdout.write(text)
    else:
        with open(args.output, "w") as f:
            f.write(text)


if __name__ == "__main__":
    main()
