# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "ahci"
        "nvme"
        "usbhid"
        "usb_storage"
        "sd_mod"
      ];
      kernelModules = [ "amdgpu" ];
      # Only root LUKS device in initrd; data drives unlock post-boot via data-drives.nix
      luks.devices = {
        "luks-bf7e5885-6a8e-447b-bb6d-b682b2991325" = {
          device = "/dev/disk/by-uuid/bf7e5885-6a8e-447b-bb6d-b682b2991325";
          allowDiscards = true;
        };
      };
    };
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };

  fileSystems = {
    "/" = {
      device = "/dev/mapper/luks-bf7e5885-6a8e-447b-bb6d-b682b2991325";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/4E54-4A55";
      fsType = "vfat";
      options = [
        "fmask=0077"
        "dmask=0077"
      ];
    };

    # Data drives managed by data-drives.nix
  };

  # 64 GiB swapfile on the LUKS-backed root, replacing the 8 GiB random-encrypted
  # partition on nvme1n1p1: that partition ran completely full for hours at a time
  # with 20-56% of RAM still free, and faulting those pages back in stalled the
  # desktop. Root is already encrypted, so dropping randomEncryption keeps swap
  # encrypted at rest. nvme1n1p1 is now unused and free to repartition.
  swapDevices = [
    {
      device = "/swapfile";
      size = 64 * 1024;
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp11s0u2u3i5.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp8s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
