name: Delete old container images

on:
  workflow_dispatch: {}
  workflow_run:
    workflows: [Docker]
    types:
      - completed

jobs:
  clean-ghcr:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    name: Delete old unused container images
    runs-on: ubuntu-latest
    steps:
      - name: Delete old images
        uses: snok/container-retention-policy@v2
        with:
          image-names: dotfiles*
          cut-off: 0 minutes ago UTC
          keep-at-least: 0
          account-type: personal
          skip-tags: latest, v*
          token: ${{ secrets.PAT }}
